# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 39323a13a560b2401f17617f0360ffff1e0a4f600038afc08b0fc9801f6f778f669d21941054449f5886d6ec12d33cb94a0e612c49d1a4a66b0417cf8486ca91

test:
  secret_key_base: b2beac9964236fd24210f6b92a7632bf37692b0bd7ad1257a6b503e60c7baffa6eb902d5869a7e37ab924b12a95bfb8d323f72524b50b619f13ad09ff0e8322b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
